In [23]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report,confusion_matrix
import warnings
import pickle
from scipy import stats
warnings.filterwarnings('ignore')
plt.style.use('fivethirtyeight')

In [24]:
df = pd.read_csv("insurance_claims.csv")

df.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,2014-10-17,OH,250/500,1000,1406.91,0,466132,...,YES,71610,6510,13020,52080,Saab,92x,2004,Y,NaN
1,228,42,342868,2006-06-27,IN,250/500,2000,1197.22,5000000,468176,...,?,5070,780,780,3510,Mercedes,E400,2007,Y,NaN
2,134,29,687698,2000-09-06,OH,100/300,2000,1413.14,5000000,430632,...,NO,34650,7700,3850,23100,Dodge,RAM,2007,N,NaN
3,256,41,227811,1990-05-25,IL,250/500,2000,1415.74,6000000,608117,...,NO,63400,6340,6340,50720,Chevrolet,Tahoe,2014,Y,NaN
4,228,44,367455,2014-06-06,IL,500/1000,1000,1583.91,6000000,610706,...,NO,6500,1300,650,4550,Accura,RSX,2009,N,NaN

In [25]:
le = LabelEncoder()

for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

df.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,fraud_reported,_c39
0,328,48,521585,940,2,1,1000,1406.91,0,466132,...,2,71610,6510,13020,52080,10,1,2004,1,NaN
1,228,42,342868,635,1,1,2000,1197.22,5000000,468176,...,0,5070,780,780,3510,8,12,2007,1,NaN
2,134,29,687698,413,2,0,2000,1413.14,5000000,430632,...,1,34650,7700,3850,23100,4,30,2007,0,NaN
3,256,41,227811,19,0,1,2000,1415.74,6000000,608117,...,1,63400,6340,6340,50720,3,34,2014,1,NaN
4,228,44,367455,922,0,2,1000,1583.91,6000000,610706,...,1,6500,1300,650,4550,0,31,2009,0,NaN

In [26]:
X = df.drop("fraud_reported", axis=1)

y = df["fraud_reported"]

print(X.shape)
print(y.shape)

(1000, 39)
(1000,)

In [27]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=0
)

print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (800, 39)
Testing Data Shape: (200, 39)

In [28]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

In [29]:
X_train = std_scaler.fit_transform(X_train)

X_train = pd.DataFrame(X_train, columns=X.columns)

X_train.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,_c39
0,-0.094195,0.199690,-1.203445,-1.205727,-1.219907,0.041858,-1.021723,-0.209017,-0.489168,1.573417,...,0.443634,-1.207406,1.646300,1.307162,2.720780,1.263562,0.850134,-1.442655,-1.030921,NaN
1,-1.749713,-1.097348,-0.740424,0.580325,1.183851,1.282100,-1.021723,-1.642830,-0.489168,1.569318,...,1.339864,1.294990,1.299671,0.108737,3.366941,0.922620,-0.151866,-0.993964,-0.365945,NaN
2,-1.029177,-1.529694,-1.506683,0.899393,-0.018028,0.041858,-1.021723,0.017655,-0.489168,-0.855134,...,0.443634,-1.207406,-1.788022,-1.324834,-1.340510,-1.810751,0.599634,1.428970,-0.033457,NaN
3,0.206028,-0.232656,0.026376,-0.952672,-0.018028,1.282100,-0.200237,0.317038,-0.489168,-0.932922,...,0.443634,1.294990,0.073345,0.527464,0.519275,-0.166586,0.850134,-1.442655,-0.199701,NaN
4,0.386163,0.307776,-1.139103,0.371280,-0.018028,-1.198383,-1.021723,-0.817514,-0.489168,-0.597316,...,-0.452596,-1.207406,0.843461,1.286535,-0.126887,0.878542,-0.402365,-0.276057,0.631520,NaN

In [ ]:
X_test = std_scaler.transform(X_test)

X_test = pd.DataFrame(X_test, columns=X.columns)

X_test.head()

,months_as_customer,age,policy_number,policy_bind_date,policy_state,policy_csl,policy_deductable,policy_annual_premium,umbrella_limit,insured_zip,...,witnesses,police_report_available,total_claim_amount,injury_claim,property_claim,vehicle_claim,auto_make,auto_model,auto_year,_c39
0,-0.694642,-1.205434,0.483778,-0.057813,1.183851,0.041858,-0.200237,-0.080388,-0.489168,-0.798710,...,-0.452596,-1.207406,0.287943,-0.276986,-0.288427,0.547160,1.601633,0.800802,1.130252,NaN
1,-0.643175,-0.989262,1.578938,1.405502,-1.219907,1.282100,1.442734,-0.251757,-0.489168,-0.549608,...,1.339864,-1.207406,-0.140111,0.317069,-0.613579,-0.119853,1.100634,0.172634,-0.033457,NaN
2,-0.094195,-0.448829,-1.060788,1.354158,-1.219907,1.282100,-1.021723,0.663144,-0.489168,-0.825404,...,-1.348827,-1.207406,-1.776608,-1.295957,-1.423352,-1.781012,0.599634,0.890540,-0.365945,NaN
3,1.913014,1.496728,-0.854725,1.632885,-1.219907,-1.198383,-0.200237,0.992416,-0.489168,1.626091,...,0.443634,0.043792,-1.738939,-1.388778,-1.274238,-1.742775,-0.151866,-0.993964,1.296496,NaN
4,-1.235045,-1.529694,0.804981,-0.519912,-0.018028,-1.198383,1.442734,-1.094809,-0.489168,-0.560703,...,-1.348827,0.043792,-0.772869,-0.685399,-0.698491,-0.723138,-0.652865,0.980279,-0.864677,NaN

Decision tree model

In [31]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Initialize Model
dtc = DecisionTreeClassifier()

# Train Model
dtc.fit(X_train, y_train)

# Predictions
y_pred = dtc.predict(X_test)

# Accuracy
dtc_train_acc = accuracy_score(y_train, dtc.predict(X_train))
dtc_test_acc = accuracy_score(y_test, y_pred)

print("Decision Tree Train Accuracy:", dtc_train_acc)
print("Decision Tree Test Accuracy:", dtc_test_acc)

Decision Tree Train Accuracy: 1.0
Decision Tree Test Accuracy: 0.75

Random forest model

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Initialize Model
rfc = RandomForestClassifier()

# Train Model
rfc.fit(X_train, y_train)

# Predictions
y_pred_rf = rfc.predict(X_test)

# Accuracy
rf_train_acc = accuracy_score(y_train, rfc.predict(X_train))
rf_test_acc = accuracy_score(y_test, y_pred_rf)

print("Random Forest Train Accuracy:", rf_train_acc)
print("Random Forest Test Accuracy:", rf_test_acc)

Random Forest Train Accuracy: 1.0
Random Forest Test Accuracy: 0.755

In [33]:
# Drop useless column with many missing values
df.drop('_c39', axis=1, inplace=True)

In [34]:
X = df.drop("fraud_reported", axis=1)
y = df["fraud_reported"]

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=0
)

In [36]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

KNN Model

In [37]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

knn = KNeighborsClassifier(n_neighbors=30)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[143   0]
 [ 56   1]]
              precision    recall  f1-score   support

           0       0.72      1.00      0.84       143
           1       1.00      0.02      0.03        57

    accuracy                           0.72       200
   macro avg       0.86      0.51      0.44       200
weighted avg       0.80      0.72      0.61       200

Logistic Regression model

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

# Initialize Model
lg = LogisticRegression(max_iter=5000)

# Train Model
lg.fit(X_train, y_train)

# Predictions
lrg_pred = lg.predict(X_test)

# Evaluation
print("Confusion Matrix:")
print(confusion_matrix(y_test, lrg_pred))

print("\nClassification Report:")
print(classification_report(y_test, lrg_pred))

print("\nAccuracy:", accuracy_score(y_test, lrg_pred))

Confusion Matrix:
[[134   9]
 [ 36  21]]

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.94      0.86       143
           1       0.70      0.37      0.48        57

    accuracy                           0.78       200
   macro avg       0.74      0.65      0.67       200
weighted avg       0.76      0.78      0.75       200


Accuracy: 0.775

Naïve Bayes model

In [39]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Initialize Model
gnb = GaussianNB()

# Train Model
model_nb = gnb.fit(X_train, y_train)

# Predictions
predict_nb = model_nb.predict(X_test)

# Accuracy
print("Training Accuracy:", 100 * accuracy_score(y_train, model_nb.predict(X_train)))
print("Testing Accuracy:", 100 * accuracy_score(y_test, predict_nb))

Training Accuracy: 73.0
Testing Accuracy: 70.0

SVM Model

In [40]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Initialize Model
svc = SVC()

# Train Model
svc.fit(X_train, y_train)

# Predictions
y_pred = svc.predict(X_test)

# Accuracy
svc_train_acc = accuracy_score(y_train, svc.predict(X_train))
svc_test_acc = accuracy_score(y_test, y_pred)

print("Training accuracy of SVC:", svc_train_acc)
print("Test accuracy of SVC:", svc_test_acc)

# Evaluation
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Training accuracy of SVC: 0.8675
Test accuracy of SVC: 0.72

Confusion Matrix:
[[143   0]
 [ 56   1]]

Classification Report:
              precision    recall  f1-score   support

           0       0.72      1.00      0.84       143
           1       1.00      0.02      0.03        57

    accuracy                           0.72       200
   macro avg       0.86      0.51      0.44       200
weighted avg       0.80      0.72      0.61       200

Test Prediction Using Decision Tree

In [ ]:
prediction = dtc.predict([[328,521585,2012,12,250,1000,1406.91,5600,1,100,25,25,50000,0,120,23,56,52,1,123,2,3,1,0,2,1,150000,2,25,2002,10,20,30,40,50,60,70,80,90]])

print("Prediction:", prediction)

Prediction: [0]

Model analysis

In [42]:
def comparison(X_test, y_test):

    print("Logistic Regression:", 100 * accuracy_score(y_test, lrg_pred))
    print("-"*100)

    print("KNN:", 100 * accuracy_score(y_test, y_pred_knn))
    print("-"*100)

    print("SVM:", 100 * svc_test_acc)
    print("-"*100)

    print("Naive Bayes:", 100 * accuracy_score(y_test, predict_nb))
    print("-"*100)

    print("Decision Tree:", 100 * dtc_test_acc)
    print("-"*100)

    print("Random Forest:", 100 * rf_test_acc)
    print("-"*100)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Initialize model
knn = KNeighborsClassifier(n_neighbors=30)

# Train
knn.fit(X_train, y_train)

# Prediction
y_pred_knn = knn.predict(X_test)

# Evaluation
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

[[143   0]
 [ 56   1]]
              precision    recall  f1-score   support

           0       0.72      1.00      0.84       143
           1       1.00      0.02      0.03        57

    accuracy                           0.72       200
   macro avg       0.86      0.51      0.44       200
weighted avg       0.80      0.72      0.61       200

In [44]:
comparison(X_test, y_test)

Logistic Regression: 77.5
----------------------------------------------------------------------------------------------------
KNN: 72.0
----------------------------------------------------------------------------------------------------
SVM: 72.0
----------------------------------------------------------------------------------------------------
Naive Bayes: 70.0
----------------------------------------------------------------------------------------------------
Decision Tree: 75.0
----------------------------------------------------------------------------------------------------
Random Forest: 75.5
----------------------------------------------------------------------------------------------------

In [45]:
from sklearn.model_selection import cross_val_score

# Perform Cross Validation
cv = cross_val_score(dtc, X_train, y_train, cv=11)

# Print Cross Validation Scores
print(cv)

# Print Average Score
print("Average Cross Validation Score:", cv.mean())

[0.76712329 0.80821918 0.80821918 0.73972603 0.82191781 0.73972603
 0.84931507 0.76712329 0.83333333 0.79166667 0.88888889]
Average Cross Validation Score: 0.8013871592638716

In [46]:
import pandas as pd

df = pd.read_csv("insurance_claims.csv")

In [57]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Features and target
X = df.drop("fraud_reported", axis=1)
y = df["fraud_reported"]

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=0
)

# Scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train final model
dtc = DecisionTreeClassifier()

dtc.fit(X_train, y_train)

# Save scaler
pickle.dump(scaler, open("std_scaler.pkl","wb"))

# Save model
pickle.dump(dtc, open("dtc_model.pkl","wb"))